apt:
  sources:
  - deb http://in.archive.ubuntu.com/ubuntu/ focal main restricted
  - deb http://in.archive.ubuntu.com/ubuntu/ focal-updates main restricted
  - deb http://in.archive.ubuntu.com/ubuntu/ focal universe
  - deb http://in.archive.ubuntu.com/ubuntu/ focal-updates universe
  - deb http://in.archive.ubuntu.com/ubuntu/ focal multiverse
  - deb http://in.archive.ubuntu.com/ubuntu/ focal-updates multiverse
  - deb http://in.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe
    multiverse
  - deb http://security.ubuntu.com/ubuntu focal-security main restricted
  - deb http://security.ubuntu.com/ubuntu focal-security universe
  - deb http://security.ubuntu.com/ubuntu focal-security multiverse
  packages:
  - libc6:amd64=2.31-0ubuntu9.16
  - gcc-10-base:amd64=10.5.0-1ubuntu1~20.04
  - libgcc-s1:amd64=10.5.0-1ubuntu1~20.04
  - libcrypt1:amd64=1:4.4.10-10ubuntu4
