# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu20/Downloads/VoIP-software-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu20/Downloads/VoIP-software-master/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"doc\" \"mumble_client\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu20/Downloads/VoIP-software-master/build/CMakeFiles /home/ubuntu20/Downloads/VoIP-software-master/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu20/Downloads/VoIP-software-master/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_license_header

# Build rule for target.
generate_license_header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_license_header
.PHONY : generate_license_header

# fast build rule for target.
generate_license_header/fast:
	$(MAKE) -f src/CMakeFiles/generate_license_header.dir/build.make src/CMakeFiles/generate_license_header.dir/build
.PHONY : generate_license_header/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) -f src/CMakeFiles/shared.dir/build.make src/CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named shared_autogen

# Build rule for target.
shared_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shared_autogen
.PHONY : shared_autogen

# fast build rule for target.
shared_autogen/fast:
	$(MAKE) -f src/CMakeFiles/shared_autogen.dir/build.make src/CMakeFiles/shared_autogen.dir/build
.PHONY : shared_autogen/fast

#=============================================================================
# Target rules for targets named TracyClient

# Build rule for target.
TracyClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TracyClient
.PHONY : TracyClient

# fast build rule for target.
TracyClient/fast:
	$(MAKE) -f src/tracy/CMakeFiles/TracyClient.dir/build.make src/tracy/CMakeFiles/TracyClient.dir/build
.PHONY : TracyClient/fast

#=============================================================================
# Target rules for targets named mumble

# Build rule for target.
mumble: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mumble
.PHONY : mumble

# fast build rule for target.
mumble/fast:
	$(MAKE) -f src/mumble/CMakeFiles/mumble.dir/build.make src/mumble/CMakeFiles/mumble.dir/build
.PHONY : mumble/fast

#=============================================================================
# Target rules for targets named mumble_client_object_lib

# Build rule for target.
mumble_client_object_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mumble_client_object_lib
.PHONY : mumble_client_object_lib

# fast build rule for target.
mumble_client_object_lib/fast:
	$(MAKE) -f src/mumble/CMakeFiles/mumble_client_object_lib.dir/build.make src/mumble/CMakeFiles/mumble_client_object_lib.dir/build
.PHONY : mumble_client_object_lib/fast

#=============================================================================
# Target rules for targets named smallft

# Build rule for target.
smallft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smallft
.PHONY : smallft

# fast build rule for target.
smallft/fast:
	$(MAKE) -f src/mumble/CMakeFiles/smallft.dir/build.make src/mumble/CMakeFiles/smallft.dir/build
.PHONY : smallft/fast

#=============================================================================
# Target rules for targets named mumble_autogen

# Build rule for target.
mumble_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mumble_autogen
.PHONY : mumble_autogen

# fast build rule for target.
mumble_autogen/fast:
	$(MAKE) -f src/mumble/CMakeFiles/mumble_autogen.dir/build.make src/mumble/CMakeFiles/mumble_autogen.dir/build
.PHONY : mumble_autogen/fast

#=============================================================================
# Target rules for targets named mumble_client_object_lib_autogen

# Build rule for target.
mumble_client_object_lib_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mumble_client_object_lib_autogen
.PHONY : mumble_client_object_lib_autogen

# fast build rule for target.
mumble_client_object_lib_autogen/fast:
	$(MAKE) -f src/mumble/CMakeFiles/mumble_client_object_lib_autogen.dir/build.make src/mumble/CMakeFiles/mumble_client_object_lib_autogen.dir/build
.PHONY : mumble_client_object_lib_autogen/fast

#=============================================================================
# Target rules for targets named mumble_client_object_lib_arcc_mumble_flags

# Build rule for target.
mumble_client_object_lib_arcc_mumble_flags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mumble_client_object_lib_arcc_mumble_flags
.PHONY : mumble_client_object_lib_arcc_mumble_flags

# fast build rule for target.
mumble_client_object_lib_arcc_mumble_flags/fast:
	$(MAKE) -f src/mumble/CMakeFiles/mumble_client_object_lib_arcc_mumble_flags.dir/build.make src/mumble/CMakeFiles/mumble_client_object_lib_arcc_mumble_flags.dir/build
.PHONY : mumble_client_object_lib_arcc_mumble_flags/fast

#=============================================================================
# Target rules for targets named speexdsp

# Build rule for target.
speexdsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 speexdsp
.PHONY : speexdsp

# fast build rule for target.
speexdsp/fast:
	$(MAKE) -f src/mumble/speexdsp/CMakeFiles/speexdsp.dir/build.make src/mumble/speexdsp/CMakeFiles/speexdsp.dir/build
.PHONY : speexdsp/fast

#=============================================================================
# Target rules for targets named renamenoise

# Build rule for target.
renamenoise: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 renamenoise
.PHONY : renamenoise

# fast build rule for target.
renamenoise/fast:
	$(MAKE) -f src/mumble/renamenoise/CMakeFiles/renamenoise.dir/build.make src/mumble/renamenoise/CMakeFiles/renamenoise.dir/build
.PHONY : renamenoise/fast

#=============================================================================
# Target rules for targets named overlay_gl_x86

# Build rule for target.
overlay_gl_x86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 overlay_gl_x86
.PHONY : overlay_gl_x86

# fast build rule for target.
overlay_gl_x86/fast:
	$(MAKE) -f overlay_gl/CMakeFiles/overlay_gl_x86.dir/build.make overlay_gl/CMakeFiles/overlay_gl_x86.dir/build
.PHONY : overlay_gl_x86/fast

#=============================================================================
# Target rules for targets named overlay_gl

# Build rule for target.
overlay_gl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 overlay_gl
.PHONY : overlay_gl

# fast build rule for target.
overlay_gl/fast:
	$(MAKE) -f overlay_gl/CMakeFiles/overlay_gl.dir/build.make overlay_gl/CMakeFiles/overlay_gl.dir/build
.PHONY : overlay_gl/fast

#=============================================================================
# Target rules for targets named link_tester

# Build rule for target.
link_tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 link_tester
.PHONY : link_tester

# fast build rule for target.
link_tester/fast:
	$(MAKE) -f plugins/link/CMakeFiles/link_tester.dir/build.make plugins/link/CMakeFiles/link_tester.dir/build
.PHONY : link_tester/fast

#=============================================================================
# Target rules for targets named link

# Build rule for target.
link: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 link
.PHONY : link

# fast build rule for target.
link/fast:
	$(MAKE) -f plugins/link/CMakeFiles/link.dir/build.make plugins/link/CMakeFiles/link.dir/build
.PHONY : link/fast

#=============================================================================
# Target rules for targets named amongus

# Build rule for target.
amongus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 amongus
.PHONY : amongus

# fast build rule for target.
amongus/fast:
	$(MAKE) -f plugins/amongus/CMakeFiles/amongus.dir/build.make plugins/amongus/CMakeFiles/amongus.dir/build
.PHONY : amongus/fast

#=============================================================================
# Target rules for targets named aoc

# Build rule for target.
aoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc
.PHONY : aoc

# fast build rule for target.
aoc/fast:
	$(MAKE) -f plugins/aoc/CMakeFiles/aoc.dir/build.make plugins/aoc/CMakeFiles/aoc.dir/build
.PHONY : aoc/fast

#=============================================================================
# Target rules for targets named arma2

# Build rule for target.
arma2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arma2
.PHONY : arma2

# fast build rule for target.
arma2/fast:
	$(MAKE) -f plugins/arma2/CMakeFiles/arma2.dir/build.make plugins/arma2/CMakeFiles/arma2.dir/build
.PHONY : arma2/fast

#=============================================================================
# Target rules for targets named bf1

# Build rule for target.
bf1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf1
.PHONY : bf1

# fast build rule for target.
bf1/fast:
	$(MAKE) -f plugins/bf1/CMakeFiles/bf1.dir/build.make plugins/bf1/CMakeFiles/bf1.dir/build
.PHONY : bf1/fast

#=============================================================================
# Target rules for targets named bf1942

# Build rule for target.
bf1942: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf1942
.PHONY : bf1942

# fast build rule for target.
bf1942/fast:
	$(MAKE) -f plugins/bf1942/CMakeFiles/bf1942.dir/build.make plugins/bf1942/CMakeFiles/bf1942.dir/build
.PHONY : bf1942/fast

#=============================================================================
# Target rules for targets named bf2

# Build rule for target.
bf2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf2
.PHONY : bf2

# fast build rule for target.
bf2/fast:
	$(MAKE) -f plugins/bf2/CMakeFiles/bf2.dir/build.make plugins/bf2/CMakeFiles/bf2.dir/build
.PHONY : bf2/fast

#=============================================================================
# Target rules for targets named bf2142

# Build rule for target.
bf2142: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf2142
.PHONY : bf2142

# fast build rule for target.
bf2142/fast:
	$(MAKE) -f plugins/bf2142/CMakeFiles/bf2142.dir/build.make plugins/bf2142/CMakeFiles/bf2142.dir/build
.PHONY : bf2142/fast

#=============================================================================
# Target rules for targets named bf3

# Build rule for target.
bf3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf3
.PHONY : bf3

# fast build rule for target.
bf3/fast:
	$(MAKE) -f plugins/bf3/CMakeFiles/bf3.dir/build.make plugins/bf3/CMakeFiles/bf3.dir/build
.PHONY : bf3/fast

#=============================================================================
# Target rules for targets named bf4

# Build rule for target.
bf4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf4
.PHONY : bf4

# fast build rule for target.
bf4/fast:
	$(MAKE) -f plugins/bf4/CMakeFiles/bf4.dir/build.make plugins/bf4/CMakeFiles/bf4.dir/build
.PHONY : bf4/fast

#=============================================================================
# Target rules for targets named bf4_x86

# Build rule for target.
bf4_x86: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bf4_x86
.PHONY : bf4_x86

# fast build rule for target.
bf4_x86/fast:
	$(MAKE) -f plugins/bf4_x86/CMakeFiles/bf4_x86.dir/build.make plugins/bf4_x86/CMakeFiles/bf4_x86.dir/build
.PHONY : bf4_x86/fast

#=============================================================================
# Target rules for targets named bfbc2

# Build rule for target.
bfbc2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bfbc2
.PHONY : bfbc2

# fast build rule for target.
bfbc2/fast:
	$(MAKE) -f plugins/bfbc2/CMakeFiles/bfbc2.dir/build.make plugins/bfbc2/CMakeFiles/bfbc2.dir/build
.PHONY : bfbc2/fast

#=============================================================================
# Target rules for targets named bfheroes

# Build rule for target.
bfheroes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bfheroes
.PHONY : bfheroes

# fast build rule for target.
bfheroes/fast:
	$(MAKE) -f plugins/bfheroes/CMakeFiles/bfheroes.dir/build.make plugins/bfheroes/CMakeFiles/bfheroes.dir/build
.PHONY : bfheroes/fast

#=============================================================================
# Target rules for targets named blacklight

# Build rule for target.
blacklight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blacklight
.PHONY : blacklight

# fast build rule for target.
blacklight/fast:
	$(MAKE) -f plugins/blacklight/CMakeFiles/blacklight.dir/build.make plugins/blacklight/CMakeFiles/blacklight.dir/build
.PHONY : blacklight/fast

#=============================================================================
# Target rules for targets named borderlands

# Build rule for target.
borderlands: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 borderlands
.PHONY : borderlands

# fast build rule for target.
borderlands/fast:
	$(MAKE) -f plugins/borderlands/CMakeFiles/borderlands.dir/build.make plugins/borderlands/CMakeFiles/borderlands.dir/build
.PHONY : borderlands/fast

#=============================================================================
# Target rules for targets named borderlands2

# Build rule for target.
borderlands2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 borderlands2
.PHONY : borderlands2

# fast build rule for target.
borderlands2/fast:
	$(MAKE) -f plugins/borderlands2/CMakeFiles/borderlands2.dir/build.make plugins/borderlands2/CMakeFiles/borderlands2.dir/build
.PHONY : borderlands2/fast

#=============================================================================
# Target rules for targets named breach

# Build rule for target.
breach: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 breach
.PHONY : breach

# fast build rule for target.
breach/fast:
	$(MAKE) -f plugins/breach/CMakeFiles/breach.dir/build.make plugins/breach/CMakeFiles/breach.dir/build
.PHONY : breach/fast

#=============================================================================
# Target rules for targets named cod2

# Build rule for target.
cod2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cod2
.PHONY : cod2

# fast build rule for target.
cod2/fast:
	$(MAKE) -f plugins/cod2/CMakeFiles/cod2.dir/build.make plugins/cod2/CMakeFiles/cod2.dir/build
.PHONY : cod2/fast

#=============================================================================
# Target rules for targets named cod4

# Build rule for target.
cod4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cod4
.PHONY : cod4

# fast build rule for target.
cod4/fast:
	$(MAKE) -f plugins/cod4/CMakeFiles/cod4.dir/build.make plugins/cod4/CMakeFiles/cod4.dir/build
.PHONY : cod4/fast

#=============================================================================
# Target rules for targets named cod5

# Build rule for target.
cod5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cod5
.PHONY : cod5

# fast build rule for target.
cod5/fast:
	$(MAKE) -f plugins/cod5/CMakeFiles/cod5.dir/build.make plugins/cod5/CMakeFiles/cod5.dir/build
.PHONY : cod5/fast

#=============================================================================
# Target rules for targets named codmw2

# Build rule for target.
codmw2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 codmw2
.PHONY : codmw2

# fast build rule for target.
codmw2/fast:
	$(MAKE) -f plugins/codmw2/CMakeFiles/codmw2.dir/build.make plugins/codmw2/CMakeFiles/codmw2.dir/build
.PHONY : codmw2/fast

#=============================================================================
# Target rules for targets named codmw2so

# Build rule for target.
codmw2so: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 codmw2so
.PHONY : codmw2so

# fast build rule for target.
codmw2so/fast:
	$(MAKE) -f plugins/codmw2so/CMakeFiles/codmw2so.dir/build.make plugins/codmw2so/CMakeFiles/codmw2so.dir/build
.PHONY : codmw2so/fast

#=============================================================================
# Target rules for targets named cs

# Build rule for target.
cs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cs
.PHONY : cs

# fast build rule for target.
cs/fast:
	$(MAKE) -f plugins/cs/CMakeFiles/cs.dir/build.make plugins/cs/CMakeFiles/cs.dir/build
.PHONY : cs/fast

#=============================================================================
# Target rules for targets named dys

# Build rule for target.
dys: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dys
.PHONY : dys

# fast build rule for target.
dys/fast:
	$(MAKE) -f plugins/dys/CMakeFiles/dys.dir/build.make plugins/dys/CMakeFiles/dys.dir/build
.PHONY : dys/fast

#=============================================================================
# Target rules for targets named etqw

# Build rule for target.
etqw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 etqw
.PHONY : etqw

# fast build rule for target.
etqw/fast:
	$(MAKE) -f plugins/etqw/CMakeFiles/etqw.dir/build.make plugins/etqw/CMakeFiles/etqw.dir/build
.PHONY : etqw/fast

#=============================================================================
# Target rules for targets named ffxiv

# Build rule for target.
ffxiv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffxiv
.PHONY : ffxiv

# fast build rule for target.
ffxiv/fast:
	$(MAKE) -f plugins/ffxiv/CMakeFiles/ffxiv.dir/build.make plugins/ffxiv/CMakeFiles/ffxiv.dir/build
.PHONY : ffxiv/fast

#=============================================================================
# Target rules for targets named ffxiv_x64

# Build rule for target.
ffxiv_x64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffxiv_x64
.PHONY : ffxiv_x64

# fast build rule for target.
ffxiv_x64/fast:
	$(MAKE) -f plugins/ffxiv_x64/CMakeFiles/ffxiv_x64.dir/build.make plugins/ffxiv_x64/CMakeFiles/ffxiv_x64.dir/build
.PHONY : ffxiv_x64/fast

#=============================================================================
# Target rules for targets named gmod

# Build rule for target.
gmod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmod
.PHONY : gmod

# fast build rule for target.
gmod/fast:
	$(MAKE) -f plugins/gmod/CMakeFiles/gmod.dir/build.make plugins/gmod/CMakeFiles/gmod.dir/build
.PHONY : gmod/fast

#=============================================================================
# Target rules for targets named gtaiv

# Build rule for target.
gtaiv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtaiv
.PHONY : gtaiv

# fast build rule for target.
gtaiv/fast:
	$(MAKE) -f plugins/gtaiv/CMakeFiles/gtaiv.dir/build.make plugins/gtaiv/CMakeFiles/gtaiv.dir/build
.PHONY : gtaiv/fast

#=============================================================================
# Target rules for targets named gtasa

# Build rule for target.
gtasa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtasa
.PHONY : gtasa

# fast build rule for target.
gtasa/fast:
	$(MAKE) -f plugins/gtasa/CMakeFiles/gtasa.dir/build.make plugins/gtasa/CMakeFiles/gtasa.dir/build
.PHONY : gtasa/fast

#=============================================================================
# Target rules for targets named gtav

# Build rule for target.
gtav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtav
.PHONY : gtav

# fast build rule for target.
gtav/fast:
	$(MAKE) -f plugins/gtav/CMakeFiles/gtav.dir/build.make plugins/gtav/CMakeFiles/gtav.dir/build
.PHONY : gtav/fast

#=============================================================================
# Target rules for targets named gw

# Build rule for target.
gw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gw
.PHONY : gw

# fast build rule for target.
gw/fast:
	$(MAKE) -f plugins/gw/CMakeFiles/gw.dir/build.make plugins/gw/CMakeFiles/gw.dir/build
.PHONY : gw/fast

#=============================================================================
# Target rules for targets named insurgency

# Build rule for target.
insurgency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 insurgency
.PHONY : insurgency

# fast build rule for target.
insurgency/fast:
	$(MAKE) -f plugins/insurgency/CMakeFiles/insurgency.dir/build.make plugins/insurgency/CMakeFiles/insurgency.dir/build
.PHONY : insurgency/fast

#=============================================================================
# Target rules for targets named jc2

# Build rule for target.
jc2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jc2
.PHONY : jc2

# fast build rule for target.
jc2/fast:
	$(MAKE) -f plugins/jc2/CMakeFiles/jc2.dir/build.make plugins/jc2/CMakeFiles/jc2.dir/build
.PHONY : jc2/fast

#=============================================================================
# Target rules for targets named lol

# Build rule for target.
lol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lol
.PHONY : lol

# fast build rule for target.
lol/fast:
	$(MAKE) -f plugins/lol/CMakeFiles/lol.dir/build.make plugins/lol/CMakeFiles/lol.dir/build
.PHONY : lol/fast

#=============================================================================
# Target rules for targets named lotro

# Build rule for target.
lotro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lotro
.PHONY : lotro

# fast build rule for target.
lotro/fast:
	$(MAKE) -f plugins/lotro/CMakeFiles/lotro.dir/build.make plugins/lotro/CMakeFiles/lotro.dir/build
.PHONY : lotro/fast

#=============================================================================
# Target rules for targets named ql

# Build rule for target.
ql: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ql
.PHONY : ql

# fast build rule for target.
ql/fast:
	$(MAKE) -f plugins/ql/CMakeFiles/ql.dir/build.make plugins/ql/CMakeFiles/ql.dir/build
.PHONY : ql/fast

#=============================================================================
# Target rules for targets named rl

# Build rule for target.
rl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rl
.PHONY : rl

# fast build rule for target.
rl/fast:
	$(MAKE) -f plugins/rl/CMakeFiles/rl.dir/build.make plugins/rl/CMakeFiles/rl.dir/build
.PHONY : rl/fast

#=============================================================================
# Target rules for targets named se

# Build rule for target.
se: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 se
.PHONY : se

# fast build rule for target.
se/fast:
	$(MAKE) -f plugins/se/CMakeFiles/se.dir/build.make plugins/se/CMakeFiles/se.dir/build
.PHONY : se/fast

#=============================================================================
# Target rules for targets named sr

# Build rule for target.
sr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sr
.PHONY : sr

# fast build rule for target.
sr/fast:
	$(MAKE) -f plugins/sr/CMakeFiles/sr.dir/build.make plugins/sr/CMakeFiles/sr.dir/build
.PHONY : sr/fast

#=============================================================================
# Target rules for targets named ut2004

# Build rule for target.
ut2004: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ut2004
.PHONY : ut2004

# fast build rule for target.
ut2004/fast:
	$(MAKE) -f plugins/ut2004/CMakeFiles/ut2004.dir/build.make plugins/ut2004/CMakeFiles/ut2004.dir/build
.PHONY : ut2004/fast

#=============================================================================
# Target rules for targets named ut3

# Build rule for target.
ut3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ut3
.PHONY : ut3

# fast build rule for target.
ut3/fast:
	$(MAKE) -f plugins/ut3/CMakeFiles/ut3.dir/build.make plugins/ut3/CMakeFiles/ut3.dir/build
.PHONY : ut3/fast

#=============================================================================
# Target rules for targets named ut99

# Build rule for target.
ut99: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ut99
.PHONY : ut99

# fast build rule for target.
ut99/fast:
	$(MAKE) -f plugins/ut99/CMakeFiles/ut99.dir/build.make plugins/ut99/CMakeFiles/ut99.dir/build
.PHONY : ut99/fast

#=============================================================================
# Target rules for targets named wolfet

# Build rule for target.
wolfet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wolfet
.PHONY : wolfet

# fast build rule for target.
wolfet/fast:
	$(MAKE) -f plugins/wolfet/CMakeFiles/wolfet.dir/build.make plugins/wolfet/CMakeFiles/wolfet.dir/build
.PHONY : wolfet/fast

#=============================================================================
# Target rules for targets named wow

# Build rule for target.
wow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wow
.PHONY : wow

# fast build rule for target.
wow/fast:
	$(MAKE) -f plugins/wow/CMakeFiles/wow.dir/build.make plugins/wow/CMakeFiles/wow.dir/build
.PHONY : wow/fast

#=============================================================================
# Target rules for targets named wow_x64

# Build rule for target.
wow_x64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wow_x64
.PHONY : wow_x64

# fast build rule for target.
wow_x64/fast:
	$(MAKE) -f plugins/wow_x64/CMakeFiles/wow_x64.dir/build.make plugins/wow_x64/CMakeFiles/wow_x64.dir/build
.PHONY : wow_x64/fast

#=============================================================================
# Target rules for targets named delayed_configure_files_target_2

# Build rule for target.
delayed_configure_files_target_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 delayed_configure_files_target_2
.PHONY : delayed_configure_files_target_2

# fast build rule for target.
delayed_configure_files_target_2/fast:
	$(MAKE) -f auxiliary_files/CMakeFiles/delayed_configure_files_target_2.dir/build.make auxiliary_files/CMakeFiles/delayed_configure_files_target_2.dir/build
.PHONY : delayed_configure_files_target_2/fast

#=============================================================================
# Target rules for targets named delayed_configure_files_target_1

# Build rule for target.
delayed_configure_files_target_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 delayed_configure_files_target_1
.PHONY : delayed_configure_files_target_1

# fast build rule for target.
delayed_configure_files_target_1/fast:
	$(MAKE) -f auxiliary_files/CMakeFiles/delayed_configure_files_target_1.dir/build.make auxiliary_files/CMakeFiles/delayed_configure_files_target_1.dir/build
.PHONY : delayed_configure_files_target_1/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... generate_license_header"
	@echo "... shared"
	@echo "... shared_autogen"
	@echo "... TracyClient"
	@echo "... mumble"
	@echo "... mumble_client_object_lib"
	@echo "... smallft"
	@echo "... mumble_autogen"
	@echo "... mumble_client_object_lib_autogen"
	@echo "... mumble_client_object_lib_arcc_mumble_flags"
	@echo "... speexdsp"
	@echo "... renamenoise"
	@echo "... overlay_gl_x86"
	@echo "... overlay_gl"
	@echo "... link_tester"
	@echo "... link"
	@echo "... amongus"
	@echo "... aoc"
	@echo "... arma2"
	@echo "... bf1"
	@echo "... bf1942"
	@echo "... bf2"
	@echo "... bf2142"
	@echo "... bf3"
	@echo "... bf4"
	@echo "... bf4_x86"
	@echo "... bfbc2"
	@echo "... bfheroes"
	@echo "... blacklight"
	@echo "... borderlands"
	@echo "... borderlands2"
	@echo "... breach"
	@echo "... cod2"
	@echo "... cod4"
	@echo "... cod5"
	@echo "... codmw2"
	@echo "... codmw2so"
	@echo "... cs"
	@echo "... dys"
	@echo "... etqw"
	@echo "... ffxiv"
	@echo "... ffxiv_x64"
	@echo "... gmod"
	@echo "... gtaiv"
	@echo "... gtasa"
	@echo "... gtav"
	@echo "... gw"
	@echo "... insurgency"
	@echo "... jc2"
	@echo "... lol"
	@echo "... lotro"
	@echo "... ql"
	@echo "... rl"
	@echo "... se"
	@echo "... sr"
	@echo "... ut2004"
	@echo "... ut3"
	@echo "... ut99"
	@echo "... wolfet"
	@echo "... wow"
	@echo "... wow_x64"
	@echo "... delayed_configure_files_target_2"
	@echo "... delayed_configure_files_target_1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

